### PR TITLE
Added Packet Pushers to podcast list

### PR DESCRIPTION
**Pull request by WilliamMarti**

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
Hi, so I purposely did not put network specific blogs and podcasts as I felt that would open up the entire networking space. There is a blurred line here so up to what the community says. 

My thought process so far was no to packet pushers and Ivan's blog, but yes to Ivan's podcast since it was automation centric, as an example.

Let me know what you and others think

**Comment by WilliamMarti** [comment]
Yeah I see what you mean about having automation focus.   The podcast isn't 100% automation focused but has had episodes that are dedicated to automation.  Not sure where the line should be drawn as I think there is some value in the podcast, but also don't want to have a huge list no one will read.

**Comment by itdependsnetworks** [comment]
I have come up with what I think is a reasonable process for this, and is described here: https://github.com/itdependsnetworks/awesome-network-automation/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Will close this in the mean time.

**Comment by WilliamMarti** [comment]
Looks fair

**Pull request closed without merging**
