### PR TITLE
Add blog and basic python topic link

### PR DESCRIPTION
**Pull request by joeryan**
Blog - Python for Network Engineers, Python Basics - pythoncentral.io

Blog link:
  - Python for Network engineers, Kirk Byers Blog
   Articles on netmiko, NAPALM, and ansible

  - Basic python topics link:
    Python Central - documentation on the library, a guide to learning the language, tips and tricks, and recipes

### CODE REVIEW

**Comment by itdependsnetworks** [comment]
As someone who works at network to code I appreciate you linking back to us instead of @ktbyers :) However, I'm not sure Kirk (or Krik) would feel. 

Do you mind updating to Kirk's blog link and name spelling?

**Comment by ktbyers** [comment]
Probably not to good :-)

Thanks, Krik

**Comment by joeryan** [comment]
My apologies on both counts.  I'm not sure how I let either of those slip through.

**Comment by ktbyers** [comment]
It is all good @joeryan

**Comment by itdependsnetworks** [comment]
No reason to apologize to me, I tried to stick an NTC sticker on Kirk's laptop during ansiblefest, so I know how it goes. :)

**Pull request merged**
